Membrane components, mechanism, and examples  (#286)
* Membrane Model Updates

The addition of all membrane components,  transport mechanism, associated unit tests, and an example.

* Update 7. Transport_Models.ipynb

Spelling mistakes

* minor changes to PR

* attempt to fix tests

* Minor changes to address pull comments

These changes do not address the comment about representing the complexes and parameters differently.

* Update components_membrane.py

* Update on transport mechanism and components (#12)

* Implementing cell identification

Updates on identification on cell identities aimed to allow multiple cells/cellular compartment.

* Create 8. Multicellular_Transport.ipynb

Examples using membrane components and transport mechanism with multiple cellular compartments.

* Updates for multi-cell transport

* Update 8. Multicellular_Transport.ipynb

* Update components_membrane.py

Attempt to fix "ERROR Tests/Unit/test_transport.py - AttributeError: 'Species' object has no attribute 'cell'"

* Update components_membrane.py

To Fix "This branch has conflicts that must be resolved" in what the IntegralMembraneProtein was initializing

* Update to fix unit tests

Minor changes in code to fix unit tests

* Update components_membrane.py

* Update components_membrane.py

* Update components_membrane.py

* Update components_membrane.py

* Update components_membrane.py

Address error "FAILED Tests/Unit/test_component_membrane.py::test_MembranePump - AttributeError: 'Species' object has no attribute 'cell'"

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Updates to Special Example 7 and 8

Minor updates to pass the unit tests required in Pull Request.

* Update components_membrane.py

* Update components_membrane.py

* update linter action yml to fix deprecated v1 and v2 of upload-artifact (#14)

* Updates to membrane components/mechanisms and examples (#16)

* update linter action yml to fix deprecated v1 and v2 of upload-artifact (#14) (#15)

Co-authored-by: Ayush Pandey <ayush.9.pandey@gmail.com>

* Updates on membrane signaling

Only updates to  two-component signaling component and mechanism. Mechanism now requires parameters to be read from file (included) and  complexes are created in a dictionary. Additionally a test for merge on new branch.

* Update test_membrane_signaling.py

* Update test_membrane_signaling.py

* Update test_membrane_signaling.py

Trouble shooting

* Fixes to test_TCS

Test edits to fix unit tests on tcs

* Update test_membrane_signaling.py

Define sensor parameter dictionary and component for reaction updates.

* Update test_membrane_signaling.py

* Update test_membrane_signaling.py

Fixing indents

* Update test_membrane_signaling.py

* Update test_membrane_signaling.py

* Update test_membrane_signaling.py

* Updates for transport mechanism using dictionaries

Incorporation of dictionaries for mechanism that have more than one complex. Addition of use of parameter file for parameters for mechanism that have more than one parameter.

* Missed in previous comiit

* Update mechanisms_transport.py

minor error

* Update mechanisms_transport.py

* Update mechanisms_transport.py

* Update mechanisms_transport.py

* Update mechanisms_transport.py

* Updates on unit tests for transports

* Edits to test transport

* Updates to test_transport

* Updates membrane_components and unit test

* Update membrane_toolbox_parameters.txt

* Update on parameter files for membrane mechanism

* Update on parameters

* Updates on component.get_parameter in mechanisms

* Minor changes to mechanism parameter name

* Update membrane_toolbox_parameters.txt

* Update membrane_toolbox_parameters.txt

* Update mechanisms_transport.py

* Update membrane_toolbox_parameters.txt

* Update mechanisms_transport.py

* Update 7. Transport_Models.ipynb

* Update 8. Multicellular_Transport.ipynb

* Update 7. Transport_Models.ipynb

Minor edits and comments

* Update 8. Multicellular_Transport.ipynb

* Update 8. Multicellular_Transport.ipynb

* Cleaning-up code

This final pass was to clean-up the code removing debugging comments and adding descriptions to the membrane parameter file.

* Update test_transport.py

---------

Co-authored-by: Ayush Pandey <ayush.9.pandey@gmail.com>

* Bump minor version (membrane toolbox) pyproject.toml

* Bump minor version (membrane toolbox) in setup.py

---------

Co-authored-by: ayush9pandey <ayush.9.pandey@gmail.com>