Update on transport mechanism and components (#12)
* Implementing cell identification

Updates on identification on cell identities aimed to allow multiple cells/cellular compartment.

* Create 8. Multicellular_Transport.ipynb

Examples using membrane components and transport mechanism with multiple cellular compartments.

* Updates for multi-cell transport

* Update 8. Multicellular_Transport.ipynb

* Update components_membrane.py

Attempt to fix "ERROR Tests/Unit/test_transport.py - AttributeError: 'Species' object has no attribute 'cell'"

* Update components_membrane.py

To Fix "This branch has conflicts that must be resolved" in what the IntegralMembraneProtein was initializing

* Update to fix unit tests

Minor changes in code to fix unit tests

* Update components_membrane.py

* Update components_membrane.py

* Update components_membrane.py

* Update components_membrane.py

* Update components_membrane.py

Address error "FAILED Tests/Unit/test_component_membrane.py::test_MembranePump - AttributeError: 'Species' object has no attribute 'cell'"

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Update 7. Transport_Models.ipynb

* Updates to Special Example 7 and 8

Minor updates to pass the unit tests required in Pull Request.

* Update components_membrane.py

* Update components_membrane.py